server:
  port: 9099
#开发配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/es_db?serverTimezone=GMT%2B8
    username: root
    password: ls123
    ## Elasticsearch配置文件（必须）
    ## 该配置和Elasticsearch的elasticsearch.yml中的配置信息有关
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.221.132:9300
logging:
  level:
    com.ls.dao: debug